// Config estratta dall'inline <script id="tailwind-config"> che ogni pagina
// portava con sé per far funzionare la Tailwind Play CDN (identica su
// index.html, asta.html, fantalistone.html, iscriviti.html — un sottoinsieme
// su privacy.html, ma con gli stessi valori esadecimali, quindi compatibile).
// Ora è la fonte unica usata per generare assets/tailwind.css una volta sola,
// vedi CLAUDE.md per il comando di rebuild.
module.exports = {
  darkMode: "class",
  content: [
    "./index.html",
    "./asta.html",
    "./fantalistone.html",
    "./iscriviti.html",
    "./privacy.html",
  ],
  theme: {
    extend: {
      colors: {
        "surface-container": "#201f1f",
        "on-primary-fixed": "#351000",
        "surface-container-high": "#2a2a2a",
        "on-primary-fixed-variant": "#7a3000",
        "surface-container-low": "#1c1b1b",
        "on-error-container": "#ffdad6",
        "tertiary-container": "#059eff",
        "on-surface-variant": "#e2bfb0",
        "primary-fixed": "#ffdbcc",
        "on-secondary-container": "#ffa173",
        "surface-container-lowest": "#0e0e0e",
        "error-container": "#93000a",
        "primary-fixed-dim": "#ffb693",
        "error": "#ffb4ab",
        "surface-container-highest": "#353534",
        "outline-variant": "#5a4136",
        "secondary-fixed": "#ffdbcc",
        "on-tertiary-container": "#003357",
        "on-surface": "#e5e2e1",
        "secondary": "#ffb693",
        "on-secondary": "#561f00",
        "surface-bright": "#393939",
        "secondary-container": "#7b3409",
        "inverse-primary": "#a04100",
        "on-tertiary-fixed": "#001d35",
        "surface": "#131313",
        "on-primary-container": "#ff6b00",
        "surface-tint": "#ffb693",
        "primary": "#ffb693",
        "outline": "#a98a7d",
        "on-background": "#e5e2e1",
        "tertiary": "#9ccaff",
        "inverse-surface": "#e5e2e1",
        "background": "#131313",
        "primary-container": "#ff6b00",
        "tertiary-fixed": "#d0e4ff",
        "surface-variant": "#353534",
        "on-primary": "#561f00",
        "surface-dim": "#131313",
        "tertiary-fixed-dim": "#9ccaff",
        "on-error": "#690005",
        "on-tertiary-fixed-variant": "#00497b",
        "on-secondary-fixed": "#351000",
        "inverse-on-surface": "#313030",
        "secondary-fixed-dim": "#ffb693",
        "on-secondary-fixed-variant": "#783207",
        "on-tertiary": "#003257",
      },
      fontFamily: {
        "headline": ["Space Grotesk"],
        "body": ["Plus Jakarta Sans"],
        "label": ["Plus Jakarta Sans"],
      },
      borderRadius: { "DEFAULT": "0.125rem", "lg": "0.25rem", "xl": "0.5rem", "full": "0.75rem" },
    },
  },
  plugins: [
    require("@tailwindcss/forms"),
    require("@tailwindcss/container-queries"),
  ],
};
